blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/SynthienceInc/Synthience-Coder/discussions/categories/feature-requests
      about: Share and vote on feature requests for Synthience Coder
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=SynthienceInc.synthience-coder&ssr=false#review-details
      about: Enjoying Synthience Coder? Leave a review here!
